services:
  silverback_app:
    container_name: "silverback"
    image: python:3.12-slim
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    working_dir: /app
    command: >
      bash -c "pip install --upgrade pip &&
              pip install -r requirements.txt && 
              python manage.py runserver 0.0.0.0:8000"
    restart: always
    environment:
      DEBUG: "true"

