services:
  silverback_app:
    container_name: "silverback"
    build: . 
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      CREDENTIALS: "[]"
      DEBUG: false
      DJANGO_SECRET_KEY: "some-random-key"
