version: "3.9"

services:
  silverback_app:
    container_name: "silverback"
    image: python:3.12-slim
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    working_dir: /app
    command: >
      bash -c "echo 'Starting Django setup...' && 
              echo 'Installing requirements...' &&
              pip install --upgrade pip &&
              pip install -r requirements.txt && 
              echo 'Running Django server with hot reload...' &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    restart: always
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app

